import { Category } from './types';

export interface CategoryTreeItem extends Category {
  parentId?: string;
  parentSlug?: string;
  parentCategory?: string;
  sortOrder?: number;
  isActive?: boolean;
  subcategories?: CategoryTreeItem[];
}

export const COMPLETE_CATEGORIES_DATA: CategoryTreeItem[] = [
  // 1. BACKPACKS
  {
    id: 'cat-backpacks',
    name: 'Backpacks',
    slug: 'backpacks',
    description: 'Custom backpacks manufactured for schools, colleges, businesses, corporate programs, travel and bulk orders with flexible design and branding options.',
    image: 'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Backpack Manufacturer in India | LTS Bags',
    metaDescription: 'Custom backpacks manufactured in India for schools, colleges, businesses and bulk orders. Explore backpack designs and request a factory quote.',
    metaKeywords: 'backpack manufacturer in India, custom backpacks wholesale, bulk backpacks India, LTS Bags backpacks',
    sortOrder: 1,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-school-backpacks',
    name: 'School Backpacks',
    slug: 'school-backpacks',
    parentId: 'cat-backpacks',
    parentSlug: 'backpacks',
    parentCategory: 'Backpacks',
    description: 'Heavy-duty school backpacks designed for students, institutions and bulk distribution.',
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=max&q=80&w=800',
    metaTitle: 'School Backpack Manufacturer in India | LTS Bags',
    metaDescription: 'Durable custom school backpacks manufactured in India for schools, institutions and wholesale buyers. Request a factory quote.',
    metaKeywords: 'school backpack manufacturer, custom school bags India, bulk school backpacks wholesale',
    sortOrder: 11,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-college-backpacks',
    name: 'College Backpacks',
    slug: 'college-backpacks',
    parentId: 'cat-backpacks',
    parentSlug: 'backpacks',
    parentCategory: 'Backpacks',
    description: 'Trendy, multi-pocket college backpacks engineered for books, laptops and daily campus use.',
    image: 'https://images.unsplash.com/photo-1577733966973-d680bffd2e80?auto=format&fit=max&q=80&w=800',
    metaTitle: 'College Backpack Manufacturer in India | LTS Bags',
    metaDescription: 'Custom college backpacks manufactured in bulk for universities, institutes and brands. Request factory pricing.',
    metaKeywords: 'college backpack manufacturer, campus bags wholesale, student backpacks India',
    sortOrder: 12,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-laptop-backpacks',
    name: 'Laptop Backpacks',
    slug: 'laptop-backpacks',
    parentId: 'cat-backpacks',
    parentSlug: 'backpacks',
    parentCategory: 'Backpacks',
    description: 'Padded laptop backpacks with dedicated device compartments, ergonomic support and custom logo branding.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Laptop Backpack Manufacturer in India | LTS Bags',
    metaDescription: 'Custom laptop backpacks manufactured for corporate gifting, offices and tech brands in India. Get a bulk quote.',
    metaKeywords: 'laptop backpack manufacturer, custom laptop bags wholesale, padded tech backpacks India',
    sortOrder: 13,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-corporate-backpacks',
    name: 'Corporate Backpacks',
    slug: 'corporate-backpacks',
    parentId: 'cat-backpacks',
    parentSlug: 'backpacks',
    parentCategory: 'Backpacks',
    description: 'Premium corporate backpacks built for employee onboarding kits, executive gifts and business events.',
    image: 'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Corporate Backpack Manufacturer in India | LTS Bags',
    metaDescription: 'Custom corporate backpacks manufactured for employee kits, corporate gifts and events in India. Bulk quotes available.',
    metaKeywords: 'corporate backpack manufacturer, custom employee onboarding bags, wholesale business backpacks',
    sortOrder: 14,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-travel-backpacks',
    name: 'Travel Backpacks',
    slug: 'travel-backpacks',
    parentId: 'cat-backpacks',
    parentSlug: 'backpacks',
    parentCategory: 'Backpacks',
    description: 'High-capacity travel backpacks with reinforced stitching, weather-resistant fabric and utility compartments.',
    image: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Travel Backpack Manufacturer in India | LTS Bags',
    metaDescription: 'Custom travel backpacks manufactured in India for tour operators, travel brands and bulk buyers.',
    metaKeywords: 'travel backpack manufacturer, wholesale travel bags, bulk rucksacks India',
    sortOrder: 15,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-casual-backpacks',
    name: 'Casual Backpacks',
    slug: 'casual-backpacks',
    parentId: 'cat-backpacks',
    parentSlug: 'backpacks',
    parentCategory: 'Backpacks',
    description: 'Versatile day-to-day casual backpacks available in varied materials, colors and custom prints.',
    image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Casual Backpack Manufacturer in India | LTS Bags',
    metaDescription: 'Wholesale casual backpacks manufactured in India for brands, retail and promotional distribution.',
    metaKeywords: 'casual backpack manufacturer, daypack wholesale, custom printed casual bags',
    sortOrder: 16,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },

  // 2. LAPTOP & OFFICE BAGS
  {
    id: 'cat-laptop-office-bags',
    name: 'Laptop & Office Bags',
    slug: 'laptop-office-bags',
    description: 'Professional laptop bags, office briefcases, messenger bags and executive document holders manufactured for corporate clients and retail brands.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Laptop & Office Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom laptop and office bags manufactured in India for corporate gifting, employee kits and wholesale buyers. Request factory pricing.',
    metaKeywords: 'laptop bag manufacturer in India, office bag manufacturer, corporate briefcases wholesale, LTS Bags office bags',
    sortOrder: 2,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-executive-laptop-bags',
    name: 'Executive Laptop Bags',
    slug: 'executive-laptop-bags',
    parentId: 'cat-laptop-office-bags',
    parentSlug: 'laptop-office-bags',
    parentCategory: 'Laptop & Office Bags',
    description: 'Sophisticated executive laptop bags with high-density padding and refined branding finishes.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Executive Laptop Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom executive laptop bags manufactured in India for corporate professionals and gifting. Get a quote.',
    metaKeywords: 'executive laptop bag manufacturer, corporate laptop briefcase, custom laptop bags India',
    sortOrder: 21,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-laptop-messenger-bags',
    name: 'Laptop Messenger Bags',
    slug: 'laptop-messenger-bags',
    parentId: 'cat-laptop-office-bags',
    parentSlug: 'laptop-office-bags',
    parentCategory: 'Laptop & Office Bags',
    description: 'Over-the-shoulder laptop messenger bags designed for quick access and executive styling.',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Laptop Messenger Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Wholesale laptop messenger bags manufactured for corporate and retail programs in India.',
    metaKeywords: 'laptop messenger bag manufacturer, shoulder messenger bags wholesale, custom messenger bags',
    sortOrder: 22,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-laptop-sleeves-cases',
    name: 'Laptop Sleeves & Cases',
    slug: 'laptop-sleeves-cases',
    parentId: 'cat-laptop-office-bags',
    parentSlug: 'laptop-office-bags',
    parentCategory: 'Laptop & Office Bags',
    description: 'Slim, protective padded laptop sleeves and slipcases customizable with debossed or printed logos.',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Laptop Sleeve Manufacturer in India | LTS Bags',
    metaDescription: 'Custom branded laptop sleeves and protective cases manufactured in bulk. Request factory pricing.',
    metaKeywords: 'laptop sleeve manufacturer, neoprene laptop cases wholesale, custom branded laptop sleeves',
    sortOrder: 23,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-office-briefcases',
    name: 'Office Briefcases',
    slug: 'office-briefcases',
    parentId: 'cat-laptop-office-bags',
    parentSlug: 'laptop-office-bags',
    parentCategory: 'Laptop & Office Bags',
    description: 'Structured office briefcases with multi-divider file sections, padded laptop cradles and lockable zippers.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Office Briefcase Manufacturer in India | LTS Bags',
    metaDescription: 'Custom office briefcases manufactured in bulk for businesses, law firms and corporate executives in India.',
    metaKeywords: 'office briefcase manufacturer, corporate briefcase wholesale, executive business bag India',
    sortOrder: 24,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-document-bags-folders',
    name: 'Document Bags & Folders',
    slug: 'document-bags-folders',
    parentId: 'cat-laptop-office-bags',
    parentSlug: 'laptop-office-bags',
    parentCategory: 'Laptop & Office Bags',
    description: 'Professional document carry bags and portfolio folders tailored for seminars, conferences and office documentation.',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Document Bag & Folder Manufacturer in India | LTS Bags',
    metaDescription: 'Custom document bags and conference folders manufactured in bulk for corporate events and meetings.',
    metaKeywords: 'document bag manufacturer, conference folder wholesale, seminar file bags India',
    sortOrder: 25,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },

  // 3. SCHOOL & COLLEGE BAGS
  {
    id: 'cat-school-college-bags',
    name: 'School & College Bags',
    slug: 'school-college-bags',
    description: 'Durable institutional school bags, kindergarten bags, tuition backpacks and college carry bags manufactured to withstand heavy daily use.',
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=max&q=80&w=800',
    metaTitle: 'School & College Bag Manufacturer in India | LTS Bags',
    metaDescription: 'High-durability school and college bags manufactured in bulk in India for educational institutions, schools and distributors.',
    metaKeywords: 'school bag manufacturer in India, college bags wholesale, institutional backpacks supplier',
    sortOrder: 3,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-primary-school-bags',
    name: 'Primary School Bags',
    slug: 'primary-school-bags',
    parentId: 'cat-school-college-bags',
    parentSlug: 'school-college-bags',
    parentCategory: 'School & College Bags',
    description: 'Ergonomically weighted primary school bags with comfortable padded shoulder straps and reflective safety trims.',
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Primary School Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom primary school bags manufactured for schools, trusts and educational institutions in India.',
    metaKeywords: 'primary school bag manufacturer, junior school backpack wholesale, kids student bags',
    sortOrder: 31,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-high-school-bags',
    name: 'High School Bags',
    slug: 'high-school-bags',
    parentId: 'cat-school-college-bags',
    parentSlug: 'school-college-bags',
    parentCategory: 'School & College Bags',
    description: 'Reinforced multi-compartment backpacks engineered to carry heavy textbooks and notebooks daily.',
    image: 'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=max&q=80&w=800',
    metaTitle: 'High School Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Durable high school backpacks manufactured in India for schools, colleges and bulk tenders.',
    metaKeywords: 'high school bag manufacturer, heavy duty student bags, bulk school backpacks',
    sortOrder: 32,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-tuition-coaching-bags',
    name: 'Tuition & Coaching Bags',
    slug: 'tuition-coaching-bags',
    parentId: 'cat-school-college-bags',
    parentSlug: 'school-college-bags',
    parentCategory: 'School & College Bags',
    description: 'Lightweight, cost-effective institute bags custom-printed with academy branding, slogans and logos.',
    image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Tuition & Coaching Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom printed tuition and coaching institute bags manufactured in bulk. Request factory quote.',
    metaKeywords: 'tuition bag manufacturer, coaching institute bags wholesale, printed class bags',
    sortOrder: 33,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-kids-character-theme-bags',
    name: 'Kids Character & Theme Bags',
    slug: 'kids-character-theme-bags',
    parentId: 'cat-school-college-bags',
    parentSlug: 'school-college-bags',
    parentCategory: 'School & College Bags',
    description: 'Colorful, fun-themed junior bags and kindergarten backpacks featuring playful graphics and soft-touch fabrics.',
    image: 'https://images.unsplash.com/photo-1577733966973-d680bffd2e80?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Kids Character Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Bulk manufacturer of vibrant kids theme and character school bags in India for retail and schools.',
    metaKeywords: 'kids character bags manufacturer, kindergarten bags wholesale, theme school bags',
    sortOrder: 34,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-school-trolley-bags',
    name: 'School Trolley Bags',
    slug: 'school-trolley-bags',
    parentId: 'cat-school-college-bags',
    parentSlug: 'school-college-bags',
    parentCategory: 'School & College Bags',
    description: 'Smooth-rolling wheeled school bags with extendable pull handles designed to reduce strain on young students.',
    image: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=max&q=80&w=800',
    metaTitle: 'School Trolley Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom rolling school trolley bags manufactured in bulk for schools and institutional luggage buyers.',
    metaKeywords: 'school trolley bag manufacturer, rolling school bags wholesale, wheeled student luggage',
    sortOrder: 35,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },

  // 4. TRAVEL BAGS
  {
    id: 'cat-travel-bags',
    name: 'Travel Bags',
    slug: 'travel-bags',
    description: 'Heavy-duty travel luggage, weekender duffels, rolling trolley bags, garment organizers and rucksacks manufactured for rugged transit and bulk distribution.',
    image: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Travel Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom travel bags, duffels and luggage manufactured in India for travel brands, corporate incentives and bulk buyers. Get a quote.',
    metaKeywords: 'travel bag manufacturer in India, custom luggage wholesale, travel duffel supplier',
    sortOrder: 4,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-travel-duffel-bags',
    name: 'Travel Duffel Bags',
    slug: 'travel-duffel-bags',
    parentId: 'cat-travel-bags',
    parentSlug: 'travel-bags',
    parentCategory: 'Travel Bags',
    description: 'Roomy travel duffels built from tear-resistant polyester or nylon with reinforced carry straps.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Travel Duffel Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Bulk travel duffel bags manufactured in India with custom branding and high-tensile fabrics.',
    metaKeywords: 'travel duffel bag manufacturer, custom duffel wholesale, holdall travel bags India',
    sortOrder: 41,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-rolling-travel-duffles',
    name: 'Rolling Travel Duffles',
    slug: 'rolling-travel-duffles',
    parentId: 'cat-travel-bags',
    parentSlug: 'travel-bags',
    parentCategory: 'Travel Bags',
    description: 'High-utility rolling duffels combining soft-shell duffel flexibility with heavy-duty corner-mounted wheels.',
    image: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Rolling Travel Duffel Manufacturer in India | LTS Bags',
    metaDescription: 'Custom wheeled rolling duffel bags manufactured for corporate rewards and travel brands in India.',
    metaKeywords: 'rolling travel duffel manufacturer, wheeled duffel wholesale, trolley duffel bags India',
    sortOrder: 42,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-weekender-overnight-bags',
    name: 'Weekender & Overnight Bags',
    slug: 'weekender-overnight-bags',
    parentId: 'cat-travel-bags',
    parentSlug: 'travel-bags',
    parentCategory: 'Travel Bags',
    description: 'Stylish compact travel bags crafted for 2-3 day business trips, hotel stays and weekend getaways.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Weekender Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom weekender and overnight bags manufactured for corporate gifting and retail brands in India.',
    metaKeywords: 'weekender bag manufacturer, overnight travel bags wholesale, luxury weekender duffel',
    sortOrder: 43,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-trekking-hiking-rucksacks',
    name: 'Trekking & Hiking Rucksacks',
    slug: 'trekking-hiking-rucksacks',
    parentId: 'cat-travel-bags',
    parentSlug: 'travel-bags',
    parentCategory: 'Travel Bags',
    description: 'Technical outdoor rucksacks with internal frames, waist harnesses, rain covers and gear loops.',
    image: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Trekking Rucksack Manufacturer in India | LTS Bags',
    metaDescription: 'Heavy-duty trekking rucksacks and hiking backpacks manufactured for expeditions and adventure clubs.',
    metaKeywords: 'trekking rucksack manufacturer, hiking backpack wholesale, outdoor rucksacks India',
    sortOrder: 44,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-travel-organizer-pouches',
    name: 'Travel Organizer Pouches',
    slug: 'travel-organizer-pouches',
    parentId: 'cat-travel-bags',
    parentSlug: 'travel-bags',
    parentCategory: 'Travel Bags',
    description: 'Multi-pocket utility kits for passports, toiletries, charging cables and travel accessories.',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Travel Organizer Pouch Manufacturer in India | LTS Bags',
    metaDescription: 'Custom travel organizer pouches and toiletry kits manufactured in bulk for brands and airlines.',
    metaKeywords: 'travel organizer pouch manufacturer, toiletry kit wholesale, travel accessory pouches',
    sortOrder: 45,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },

  // 5. SPORTS & GYM BAGS
  {
    id: 'cat-sports-gym-bags',
    name: 'Sports & Gym Bags',
    slug: 'sports-gym-bags',
    description: 'Athletic gear bags, gym duffels with shoe compartments, team sports bags and tournament kitbags manufactured for clubs, fitness centers and athletic brands.',
    image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Sports & Gym Bag Manufacturer in India | LTS Bags',
    metaDescription: 'High-performance sports and gym bags manufactured in India for fitness centers, athletic clubs, corporate sports and bulk buyers.',
    metaKeywords: 'sports bag manufacturer in India, gym bag manufacturer, wholesale kit bags, LTS Bags athletic gear',
    sortOrder: 5,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-gym-duffel-bags',
    name: 'Gym Duffel Bags',
    slug: 'gym-duffel-bags',
    parentId: 'cat-sports-gym-bags',
    parentSlug: 'sports-gym-bags',
    parentCategory: 'Sports & Gym Bags',
    description: 'Ventilated fitness duffels featuring separated footwear tunnels and waterproof wet-item liners.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Gym Duffel Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom gym duffel bags manufactured in bulk with shoe pockets and wet compartments. Factory quotes.',
    metaKeywords: 'gym duffel bag manufacturer, custom workout bags wholesale, fitness duffel with shoe pocket',
    sortOrder: 51,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-sports-kit-bags',
    name: 'Sports Kit Bags',
    slug: 'sports-kit-bags',
    parentId: 'cat-sports-gym-bags',
    parentSlug: 'sports-gym-bags',
    parentCategory: 'Sports & Gym Bags',
    description: 'Oversized heavy-duty equipment bags engineered to carry full athletic gear sets and team uniforms.',
    image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Sports Kit Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Bulk manufacturer of sports kit bags for cricket, football, hockey and athletics teams in India.',
    metaKeywords: 'sports kit bag manufacturer, athletic gear bags wholesale, team tournament bags',
    sortOrder: 52,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-drawstring-gym-bags',
    name: 'Drawstring Gym Bags',
    slug: 'drawstring-gym-bags',
    parentId: 'cat-sports-gym-bags',
    parentSlug: 'sports-gym-bags',
    parentCategory: 'Sports & Gym Bags',
    description: 'Lightweight cinch-string backpacks ideal for daily workout essentials, swim classes and athletic meets.',
    image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Drawstring Gym Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom drawstring sports bags manufactured in bulk for fitness clubs, marathons and events in India.',
    metaKeywords: 'drawstring gym bag manufacturer, cinch bag wholesale, sports drawstring backpacks',
    sortOrder: 53,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-yoga-mat-carry-bags',
    name: 'Yoga Mat Carry Bags',
    slug: 'yoga-mat-carry-bags',
    parentId: 'cat-sports-gym-bags',
    parentSlug: 'sports-gym-bags',
    parentCategory: 'Sports & Gym Bags',
    description: 'Form-fitting breathable yoga mat carriers with adjustable shoulder slings and accessory pockets.',
    image: 'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Yoga Mat Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom yoga mat carry bags and studio totes manufactured in India. Request wholesale pricing.',
    metaKeywords: 'yoga mat bag manufacturer, yoga mat carrier wholesale, studio fitness bags India',
    sortOrder: 54,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-shoe-bags',
    name: 'Shoe Bags',
    slug: 'shoe-bags',
    parentId: 'cat-sports-gym-bags',
    parentSlug: 'sports-gym-bags',
    parentCategory: 'Sports & Gym Bags',
    description: 'Compact zippered dust and water-resistant shoe bags for athletes, golfers and travelers.',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Shoe Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom printed sports shoe bags and travel shoe pouches manufactured in bulk. Request factory pricing.',
    metaKeywords: 'shoe bag manufacturer, sports footwear bag wholesale, travel shoe pouch India',
    sortOrder: 55,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },

  // 6. CORPORATE & PROMOTIONAL BAGS
  {
    id: 'cat-corporate-promotional-bags',
    name: 'Corporate & Promotional Bags',
    slug: 'corporate-promotional-bags',
    description: 'Customized corporate gifting bags, employee onboarding backpacks, exhibition tote giveaways and conference bags manufactured to promote brand recall.',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Corporate & Promotional Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom corporate gifting and promotional bags manufactured in bulk in India. High-impact logo branding, fast production and factory pricing.',
    metaKeywords: 'corporate bag manufacturer in India, promotional bags wholesale, custom gifting bags India',
    sortOrder: 6,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-employee-onboarding-bags',
    name: 'Employee Onboarding Bags',
    slug: 'employee-onboarding-bags',
    parentId: 'cat-corporate-promotional-bags',
    parentSlug: 'corporate-promotional-bags',
    parentCategory: 'Corporate & Promotional Bags',
    description: 'Sophisticated tech-ready backpacks curated specifically for new-hire welcome kits and employee milestone gifts.',
    image: 'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Employee Onboarding Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom employee welcome kit backpacks and onboarding bags manufactured in bulk for corporate HRs.',
    metaKeywords: 'employee onboarding bag manufacturer, welcome kit backpack wholesale, corporate HR bags',
    sortOrder: 61,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-conference-seminar-bags',
    name: 'Conference & Seminar Bags',
    slug: 'conference-seminar-bags',
    parentId: 'cat-corporate-promotional-bags',
    parentSlug: 'corporate-promotional-bags',
    parentCategory: 'Corporate & Promotional Bags',
    description: 'Practical document bags and folders designed for trade conferences, annual summits and delegate gift packs.',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Conference Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom conference bags and delegate document carriers manufactured in bulk for events and summits.',
    metaKeywords: 'conference bag manufacturer, seminar bag wholesale, delegate document holders',
    sortOrder: 62,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-exhibition-trade-show-bags',
    name: 'Exhibition & Trade Show Bags',
    slug: 'exhibition-trade-show-bags',
    parentId: 'cat-corporate-promotional-bags',
    parentSlug: 'corporate-promotional-bags',
    parentCategory: 'Corporate & Promotional Bags',
    description: 'High-visibility branded carry bags designed for maximum brand impressions at trade expos and exhibitions.',
    image: 'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Trade Show Exhibition Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Bulk promotional exhibition bags and giveaway totes manufactured with custom full-color branding.',
    metaKeywords: 'exhibition bag manufacturer, trade show tote wholesale, promotional event bags',
    sortOrder: 63,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-promotional-drawstring-bags',
    name: 'Promotional Drawstring Bags',
    slug: 'promotional-drawstring-bags',
    parentId: 'cat-corporate-promotional-bags',
    parentSlug: 'corporate-promotional-bags',
    parentCategory: 'Corporate & Promotional Bags',
    description: 'Cost-effective cinch-string giveaway packs with large billboard print areas for marketing campaigns.',
    image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Promotional Drawstring Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Bulk promotional drawstring bags manufactured in India for marathons, campaigns and brand giveaways.',
    metaKeywords: 'promotional drawstring bag manufacturer, cinch sack wholesale, giveaway drawstring bags',
    sortOrder: 64,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-custom-branded-giveaways',
    name: 'Custom Branded Giveaways',
    slug: 'custom-branded-giveaways',
    parentId: 'cat-corporate-promotional-bags',
    parentSlug: 'corporate-promotional-bags',
    parentCategory: 'Corporate & Promotional Bags',
    description: 'Bespoke promotional bags tailored with custom colors, brand tags and corporate identity printing.',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Custom Branded Promotional Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom branded giveaway bags manufactured in bulk for corporate marketing campaigns across India.',
    metaKeywords: 'custom branded bag manufacturer, marketing giveaway bags, corporate identity merchandise',
    sortOrder: 65,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },

  // 7. TOTE & SHOPPING BAGS
  {
    id: 'cat-tote-shopping-bags',
    name: 'Tote & Shopping Bags',
    slug: 'tote-shopping-bags',
    description: 'Reusable canvas tote bags, cotton shopping bags, grocery carry bags and designer shoulder totes manufactured for sustainable retail and marketing.',
    image: 'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Canvas & Tote Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom canvas tote bags and shopping bags manufactured in India for retail brands, exhibitions and eco-conscious bulk buyers.',
    metaKeywords: 'tote bag manufacturer in India, canvas tote bags wholesale, custom shopping bags India',
    sortOrder: 7,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-canvas-tote-bags',
    name: 'Canvas Tote Bags',
    slug: 'canvas-tote-bags',
    parentId: 'cat-tote-shopping-bags',
    parentSlug: 'tote-shopping-bags',
    parentCategory: 'Tote & Shopping Bags',
    description: 'Premium heavy-ounce canvas tote bags ideal for lifestyle brands, bookshops and corporate giveaways.',
    image: 'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Canvas Tote Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom cotton canvas tote bags manufactured in India with screen printing and embroidery options.',
    metaKeywords: 'canvas tote bag manufacturer, heavy canvas totes wholesale, custom printed tote bags',
    sortOrder: 71,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-cotton-shopping-bags',
    name: 'Cotton Shopping Bags',
    slug: 'cotton-shopping-bags',
    parentId: 'cat-tote-shopping-bags',
    parentSlug: 'tote-shopping-bags',
    parentCategory: 'Tote & Shopping Bags',
    description: 'Lightweight reusable 100% natural cotton carry bags tailored for daily grocery and retail checkout.',
    image: 'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Cotton Shopping Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Wholesale cotton shopping bags manufactured in India for grocery chains, retail stores and eco-events.',
    metaKeywords: 'cotton shopping bag manufacturer, reusable cotton bags wholesale, retail shopping carry bags',
    sortOrder: 72,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-non-woven-shopping-bags',
    name: 'Non-Woven Shopping Bags',
    slug: 'non-woven-shopping-bags',
    parentId: 'cat-tote-shopping-bags',
    parentSlug: 'tote-shopping-bags',
    parentCategory: 'Tote & Shopping Bags',
    description: 'Economical, lightweight non-woven polypropylene carry bags for retail packaging and mass promotional supply.',
    image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Non-Woven Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Bulk manufacturer of non-woven shopping bags and D-cut carry bags in India. Factory direct supply.',
    metaKeywords: 'non woven bag manufacturer, D cut shopping bags wholesale, polypropylene carry bags',
    sortOrder: 73,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-foldable-shopping-bags',
    name: 'Foldable Shopping Bags',
    slug: 'foldable-shopping-bags',
    parentId: 'cat-tote-shopping-bags',
    parentSlug: 'tote-shopping-bags',
    parentCategory: 'Tote & Shopping Bags',
    description: 'Handy pocket-sized foldable carry bags that tuck into a tiny pouch for on-the-go reusable shopping.',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Foldable Shopping Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Compact foldable pocket shopping bags manufactured in bulk for retail brands and promotional events.',
    metaKeywords: 'foldable shopping bag manufacturer, pocket grocery bags wholesale, compact reusable bags',
    sortOrder: 74,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-grocery-carry-bags',
    name: 'Grocery Carry Bags',
    slug: 'grocery-carry-bags',
    parentId: 'cat-tote-shopping-bags',
    parentSlug: 'tote-shopping-bags',
    parentCategory: 'Tote & Shopping Bags',
    description: 'High-capacity reinforced-bottom shopping bags engineered to handle heavy supermarket loads securely.',
    image: 'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Grocery Carry Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Heavy-duty reusable grocery bags manufactured in bulk for supermarket chains and organic stores in India.',
    metaKeywords: 'grocery carry bag manufacturer, supermarket reusable bags wholesale, heavy duty grocery tote',
    sortOrder: 75,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },

  // 8. JUTE & ECO BAGS
  {
    id: 'cat-jute-eco-bags',
    name: 'Jute & Eco Bags',
    slug: 'jute-eco-bags',
    description: '100% natural biodegradable jute shopping bags, juco conference bags, eco gift totes and sustainable packaging solutions manufactured for green enterprises.',
    image: 'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Jute & Eco-Friendly Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Natural jute and eco-friendly bags manufactured in India for corporate gifting, retail and sustainable brand campaigns. Get bulk pricing.',
    metaKeywords: 'jute bag manufacturer in India, eco bags wholesale, sustainable jute totes India',
    sortOrder: 8,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-jute-shopping-bags',
    name: 'Jute Shopping Bags',
    slug: 'jute-shopping-bags',
    parentId: 'cat-jute-eco-bags',
    parentSlug: 'jute-eco-bags',
    parentCategory: 'Jute & Eco Bags',
    description: 'Golden natural jute shopping totes with laminated interiors, cotton padded handles and eco-friendly inks.',
    image: 'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Jute Shopping Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Bulk natural jute shopping bags manufactured in India with cotton rope handles and custom printing.',
    metaKeywords: 'jute shopping bag manufacturer, laminated jute bags wholesale, natural fiber shopping bags',
    sortOrder: 81,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-juco-bags',
    name: 'Juco Bags (Jute-Cotton Blend)',
    slug: 'juco-bags',
    parentId: 'cat-jute-eco-bags',
    parentSlug: 'jute-eco-bags',
    parentCategory: 'Jute & Eco Bags',
    description: 'Smooth-finish hybrid jute-cotton blend bags combining the strength of jute with the fine printability of cotton.',
    image: 'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Juco Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Premium juco (jute-cotton blend) bags manufactured in India for corporate gifting and retail brands.',
    metaKeywords: 'juco bag manufacturer, jute cotton blend bags wholesale, luxury eco totes India',
    sortOrder: 82,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-jute-conference-bags',
    name: 'Jute Conference Bags',
    slug: 'jute-conference-bags',
    parentId: 'cat-jute-eco-bags',
    parentSlug: 'jute-eco-bags',
    parentCategory: 'Jute & Eco Bags',
    description: 'Elegant eco-friendly portfolio bags and document carriers crafted for sustainable business conferences.',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Jute Conference Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom eco-friendly jute conference bags and seminar folders manufactured in bulk for summits.',
    metaKeywords: 'jute conference bag manufacturer, eco seminar folders wholesale, sustainable delegate bags',
    sortOrder: 83,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-jute-gift-wine-bags',
    name: 'Jute Gift & Wine Bags',
    slug: 'jute-gift-wine-bags',
    parentId: 'cat-jute-eco-bags',
    parentSlug: 'jute-eco-bags',
    parentCategory: 'Jute & Eco Bags',
    description: 'Charming jute packaging pouches with cane or rope handles, designed for festive hampers and bottle gifting.',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Jute Gift & Wine Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom natural jute gift bags and single/double wine bottle carry pouches manufactured in India.',
    metaKeywords: 'jute gift bag manufacturer, jute wine bottle bag wholesale, festive jute pouches',
    sortOrder: 84,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-organic-cotton-bags',
    name: 'Organic Cotton Bags',
    slug: 'organic-cotton-bags',
    parentId: 'cat-jute-eco-bags',
    parentSlug: 'jute-eco-bags',
    parentCategory: 'Jute & Eco Bags',
    description: 'Pure unbleached organic cotton bags certified for eco-sensitive retail and international export standards.',
    image: 'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Organic Cotton Bag Manufacturer in India | LTS Bags',
    metaDescription: 'GOTS-certified organic cotton bags manufactured in bulk in India for global eco brands and retail stores.',
    metaKeywords: 'organic cotton bag manufacturer, GOTS certified cotton bags wholesale, sustainable cotton tote',
    sortOrder: 85,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },

  // 9. SLING & SHOULDER BAGS
  {
    id: 'cat-sling-shoulder-bags',
    name: 'Sling & Shoulder Bags',
    slug: 'sling-shoulder-bags',
    description: 'Crossbody sling bags, chest packs, single-strap shoulder bags and utility side bags manufactured for modern commuters, youth brands and corporate events.',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Sling & Crossbody Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom sling and crossbody shoulder bags manufactured in bulk in India. Modern designs, durable fabrics and factory wholesale pricing.',
    metaKeywords: 'sling bag manufacturer in India, crossbody bag wholesale, custom shoulder bags India',
    sortOrder: 9,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-crossbody-sling-bags',
    name: 'Crossbody Sling Bags',
    slug: 'crossbody-sling-bags',
    parentId: 'cat-sling-shoulder-bags',
    parentSlug: 'sling-shoulder-bags',
    parentCategory: 'Sling & Shoulder Bags',
    description: 'Compact hands-free crossbody bags with quick-release buckles and organized tech accessory pockets.',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Crossbody Sling Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom crossbody sling bags manufactured in India for retail fashion brands and corporate giveaways.',
    metaKeywords: 'crossbody sling bag manufacturer, hands free sling bags wholesale, custom crossbody bag',
    sortOrder: 91,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-chest-shoulder-packs',
    name: 'Chest & Shoulder Packs',
    slug: 'chest-shoulder-packs',
    parentId: 'cat-sling-shoulder-bags',
    parentSlug: 'sling-shoulder-bags',
    parentCategory: 'Sling & Shoulder Bags',
    description: 'Front-mount chest packs and ergonomic single-strap shoulder slings for urban commute and biking.',
    image: 'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Chest Pack & Shoulder Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Tactical and urban chest packs manufactured in bulk with custom branding for outdoor and city use.',
    metaKeywords: 'chest pack manufacturer, single strap shoulder bag wholesale, tactical chest sling',
    sortOrder: 92,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-canvas-side-bags',
    name: 'Canvas Side Bags',
    slug: 'canvas-side-bags',
    parentId: 'cat-sling-shoulder-bags',
    parentSlug: 'sling-shoulder-bags',
    parentCategory: 'Sling & Shoulder Bags',
    description: 'Vintage and casual canvas satchels with adjustable shoulder webbing and metal hardware accents.',
    image: 'https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Canvas Side Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Wholesale canvas side bags and casual shoulder satchels manufactured in India. Request bulk pricing.',
    metaKeywords: 'canvas side bag manufacturer, casual shoulder satchels wholesale, vintage canvas bags',
    sortOrder: 93,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-utility-waist-fanny-packs',
    name: 'Utility Waist & Fanny Packs',
    slug: 'utility-waist-fanny-packs',
    parentId: 'cat-sling-shoulder-bags',
    parentSlug: 'sling-shoulder-bags',
    parentCategory: 'Sling & Shoulder Bags',
    description: 'Versatile waist packs featuring dual-zip compartments, secure waist clips and waterproof fabrics.',
    image: 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Fanny Pack & Waist Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom waist bags and fanny packs manufactured in bulk for events, travel brands and sports clubs.',
    metaKeywords: 'fanny pack manufacturer, waist bag wholesale, custom bum bags India',
    sortOrder: 94,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-tech-pouch-slings',
    name: 'Tech Pouch Slings',
    slug: 'tech-pouch-slings',
    parentId: 'cat-sling-shoulder-bags',
    parentSlug: 'sling-shoulder-bags',
    parentCategory: 'Sling & Shoulder Bags',
    description: 'Structured gadget carry bags with elastic cable holders, memory card slots and power bank sleeves.',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Tech Pouch Sling Manufacturer in India | LTS Bags',
    metaDescription: 'Custom padded tech pouches and gadget sling bags manufactured for corporate gifts and IT teams in India.',
    metaKeywords: 'tech pouch sling manufacturer, gadget organizer bag wholesale, electronics sling pouch',
    sortOrder: 95,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },

  // 10. LUNCH & UTILITY BAGS
  {
    id: 'cat-lunch-utility-bags',
    name: 'Lunch & Utility Bags',
    slug: 'lunch-utility-bags',
    description: 'Insulated lunch bags, thermal food delivery bags, tool organizer bags and specialized utility pouches manufactured with food-grade and heavy-duty materials.',
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Insulated Lunch & Utility Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom insulated lunch bags and industrial utility bags manufactured in India for corporate gifting, catering and tools. Bulk quotes.',
    metaKeywords: 'lunch bag manufacturer in India, insulated lunch bags wholesale, utility bag manufacturer India',
    sortOrder: 10,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-insulated-lunch-bags',
    name: 'Insulated Lunch Bags',
    slug: 'insulated-lunch-bags',
    parentId: 'cat-lunch-utility-bags',
    parentSlug: 'lunch-utility-bags',
    parentCategory: 'Lunch & Utility Bags',
    description: 'Aluminum-foil lined thermal lunch carriers engineered to keep food warm or cool for hours.',
    image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Insulated Lunch Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom insulated thermal lunch bags manufactured for corporate employee kits and office goers in India.',
    metaKeywords: 'insulated lunch bag manufacturer, thermal meal bag wholesale, foil lined lunch bag',
    sortOrder: 101,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-office-lunch-totes',
    name: 'Office Lunch Totes',
    slug: 'office-lunch-totes',
    parentId: 'cat-lunch-utility-bags',
    parentSlug: 'lunch-utility-bags',
    parentCategory: 'Lunch & Utility Bags',
    description: 'Compact, spill-resistant executive lunch totes styled to coordinate seamlessly with professional office gear.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Office Lunch Tote Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Wholesale office lunch totes and compact meal bags manufactured in bulk with corporate logo printing.',
    metaKeywords: 'office lunch tote manufacturer, executive lunch bag wholesale, corporate meal tote',
    sortOrder: 102,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-thermal-food-delivery-bags',
    name: 'Thermal Food Delivery Bags',
    slug: 'thermal-food-delivery-bags',
    parentId: 'cat-lunch-utility-bags',
    parentSlug: 'lunch-utility-bags',
    parentCategory: 'Lunch & Utility Bags',
    description: 'Commercial-grade insulated delivery backpacks with heat-sealed leakproof linings and reflective bands.',
    image: 'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Thermal Food Delivery Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Heavy-duty commercial thermal food delivery backpacks and bags manufactured for delivery fleets.',
    metaKeywords: 'thermal food delivery bag manufacturer, courier delivery bags wholesale, insulated delivery backpack',
    sortOrder: 103,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-tool-technical-utility-bags',
    name: 'Tool & Technical Utility Bags',
    slug: 'tool-technical-utility-bags',
    parentId: 'cat-lunch-utility-bags',
    parentSlug: 'lunch-utility-bags',
    parentCategory: 'Lunch & Utility Bags',
    description: 'Rugged multi-pocket tool bags crafted from 1680D nylon with hard-base bottoms for service engineers.',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Tool Bag & Technical Utility Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Heavy-duty tool bags and technician utility backpacks manufactured with reinforced ballistic fabrics.',
    metaKeywords: 'tool bag manufacturer, technician utility bags wholesale, heavy duty tool backpacks India',
    sortOrder: 104,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-medical-kit-utility-pouches',
    name: 'Medical & Kit Utility Pouches',
    slug: 'medical-kit-utility-pouches',
    parentId: 'cat-lunch-utility-bags',
    parentSlug: 'lunch-utility-bags',
    parentCategory: 'Lunch & Utility Bags',
    description: 'Specialized compartmented utility bags with wipe-clean water-resistant linings for medical and first-aid kits.',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Medical Kit & First Aid Utility Pouch Manufacturer in India | LTS Bags',
    metaDescription: 'Custom medical kit pouches and emergency first aid bags manufactured in bulk for healthcare and institutions.',
    metaKeywords: 'medical kit pouch manufacturer, first aid bag wholesale, emergency kit bags India',
    sortOrder: 105,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },

  // 11. CUSTOM MANUFACTURING
  {
    id: 'cat-custom-manufacturing',
    name: 'Custom Manufacturing',
    slug: 'custom-manufacturing',
    description: 'End-to-end OEM and ODM custom bag manufacturing from design sketches to tech-pack development, sampling, fabric sourcing and full-scale factory production.',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=max&q=80&w=800',
    metaTitle: 'OEM & ODM Custom Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Full-service OEM/ODM custom bag manufacturing in India. Custom pattern making, rapid prototyping, certified fabrics and volume production.',
    metaKeywords: 'OEM bag manufacturer India, ODM custom bag production, made to order bags India, LTS Bags custom manufacturing',
    sortOrder: 11,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-oem-bag-manufacturing',
    name: 'OEM Bag Manufacturing',
    slug: 'oem-bag-manufacturing',
    parentId: 'cat-custom-manufacturing',
    parentSlug: 'custom-manufacturing',
    parentCategory: 'Custom Manufacturing',
    description: 'Build custom bags strictly according to your proprietary technical specifications and private-label standards.',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=max&q=80&w=800',
    metaTitle: 'OEM Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Contract OEM bag manufacturing in India for global and domestic brands with stringent quality audits.',
    metaKeywords: 'OEM bag manufacturer, contract bag manufacturing India, private label bag production',
    sortOrder: 111,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-odm-bag-design-production',
    name: 'ODM Bag Design & Production',
    slug: 'odm-bag-design-production',
    parentId: 'cat-custom-manufacturing',
    parentSlug: 'custom-manufacturing',
    parentCategory: 'Custom Manufacturing',
    description: 'Select from our in-house engineered bag patterns and customize materials, colorways and branding accents.',
    image: 'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?auto=format&fit=max&q=80&w=800',
    metaTitle: 'ODM Bag Manufacturer & Designer in India | LTS Bags',
    metaDescription: 'Original design and manufacture of custom bags for brands looking for ready-to-brand catalog models.',
    metaKeywords: 'ODM bag manufacturer, white label bag design, ready catalog bag production',
    sortOrder: 112,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-private-label-bag-manufacturing',
    name: 'Private Label Bag Manufacturing',
    slug: 'private-label-bag-manufacturing',
    parentId: 'cat-custom-manufacturing',
    parentSlug: 'custom-manufacturing',
    parentCategory: 'Custom Manufacturing',
    description: 'Complete private-label packaging including woven brand tags, wash care labels, custom pullers and retail boxes.',
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Private Label Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom private label bag manufacturing for retail brands, e-commerce labels and boutique collections.',
    metaKeywords: 'private label bag manufacturer, custom retail bags wholesale, branded bags manufacturing India',
    sortOrder: 113,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-corporate-gifting-bulk-manufacturing',
    name: 'Corporate Gifting Bulk Manufacturing',
    slug: 'corporate-gifting-bulk-manufacturing',
    parentId: 'cat-custom-manufacturing',
    parentSlug: 'custom-manufacturing',
    parentCategory: 'Custom Manufacturing',
    description: 'High-volume custom bag manufacturing programs with tiered volume pricing, premium packaging and punctual dispatch.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Corporate Gifting Bag Manufacturer in India | LTS Bags',
    metaDescription: 'Custom corporate gifting bags manufactured in large volumes for annual events, festivals and client appreciation.',
    metaKeywords: 'corporate gifting bag manufacturer, bulk festival gift bags, annual event bags wholesale',
    sortOrder: 114,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'cat-custom-pattern-sample-development',
    name: 'Custom Pattern & Sample Development',
    slug: 'custom-pattern-sample-development',
    parentId: 'cat-custom-manufacturing',
    parentSlug: 'custom-manufacturing',
    parentCategory: 'Custom Manufacturing',
    description: 'Dedicated physical golden sample prototyping with master pattern makers before bulk production sign-off.',
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=max&q=80&w=800',
    metaTitle: 'Bag Sampling & Pattern Development in India | LTS Bags',
    metaDescription: 'Rapid prototype sampling and technical pattern development for custom bag manufacturing programs.',
    metaKeywords: 'bag sampling service, pattern development bag factory, custom prototype bag maker',
    sortOrder: 115,
    isActive: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
];
